version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pa55word!"
      ACCEPT_EULA: "Y"

  postgresql-db:
    container_name: postgres-db
    command: postgres -c 'max_connections=200'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "Pa55word!"